sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories: "$HOME/.m2/repository"

install:
  - rm ~/.m2/settings.xml
  - echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/.m2/settings.xml
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then GOAL=deploy; else GOAL=install; fi

script: mvn -q -U -Psnapshots $GOAL
